### ISSUE TITLE
Firestore - ValueDeserializer fails with NullReferenceException

### ISSUE THREAD

**Issue by pauloevpr** [GoogleCloudPlatform/google-cloud-dotnet#2477]
I have found an issue when using Firestore (currently 1.0.0-beta08) in my C# project. Calling `ConvertTo<T>()` from a document snapshot fails when T has a property with `FirestorePropertyAttribute `that has a non-public setter.

The exception is `System.NullReferenceException: 'Object reference not set to an instance of an object.' System.Reflection.PropertyInfo.GetSetMethod(...) returned null.` It is coming from `ValueDeserializer.DeserializeMap()` from the linq query `targetType.GetTypeInfo().DeclaredProperties.Where(p => p.CanWrite && p.GetSetMethod().IsPublic && !p.GetSetMethod().IsStatic)`.

My main concern is actually the design. The API is intentionally looking for a public setter. That does not seem to be the best approach when it comes to mapping/converting persistent data to/from POCO classes. It is natural for domain entities in many cases to have non-public setters in order to provide non-anemic domain entities while maintaining compatibility with ORMs and other mappers.

I believe the behavior should be at least configurable.

**Comment by pauloevpr** [comment]
Thank you for your reply.

Mapping `DocumentSnapshot` to a `Dictionary<string, object>` is costly enough, provided that the current serialization capabilities are far from optimal. Applying another serialization operation on top of that will come with a performance penalty.

If the idea is to keep the library simple, I think there should be at least room for extension. The simplest solution I can think of is to expose `DocumentSnapshot.Document` as read-only property or as a method `DocumentSnapshot.GetDocumentData()`, so custom serialization operations can be applied to the raw `Document`. I don't see how this could break immutability.

**Comment by jskeet** [comment]
> If the idea is to keep the library simple, I think there should be at least room for extension. 

Working out the right extension points is itself a point of complexity. We definitely need to find a balance here, and it's probably too restrictive right now - but I'm very conservative when it comes to adding additional API aspects, simply because it's a lot easier to add functionality later than it is to remove it. (Obviously more so once the library is GA.) It becomes even more complex when things like sentinel values are involved. At the moment, the rest of the library can make assumptions about what serialization and deserialization do, because we have full control over that code. As soon as it's extensible, those assumptions become a lot more difficult.

In terms of efficiency, mapping to a `Dictionary<string, object>` with custom code is likely to be more efficient than the reflection-based serialization we're performing at the moment, to be honest. We do want to improve that over time, and I do acknowledge the cost of multiple levels of serialization.

> I don't see how this could break the immutability of DocumentSnapshot.

Well `Document` is mutable - if the code has access to it, it can mutate it and potentially cause issues with anything relying on computed snapshot ordering (e.g. for Listen operations). We *could* potentially provide access to it with a caveat of "messing with this is unsupported". I'm pretty wary of that though.

If it's just an application depending directly on Google.Cloud.Firestore, it's probably not too bad - the difficulty comes when there are multiple layers involved - if an app by developer X depends on a library by developer Y that depends on Firestore.

**Comment by pauloevpr** [comment]
Maybe getting a copy of `Document` as a `Dictionary<string, Google.Cloud.Firestore.V1Beta1.Value>` out of `DocumentSnapshot` should be enough to allow custom serialization. Cloning `Google.Cloud.Firestore.V1Beta1.Value` seems to be a lightweight operation.

**Comment by jskeet** [comment]
Okay, I've been speaking with a colleague, and for now, our plan is:

- As the properties are explicitly attributed, we *will* allow internal and private ones (both for get and set). If we ever introduce the idea of "just fetch every property" we may need more nuance on that setting, e.g. PublicProperties etc
- We'll introduce a *very* crude opt-in warning mechanism in the form of an `Action<string>` which is called with any warnings. (So you could just call `Console.WriteLine`, or do something more interesting.)
- I'll make sure that deserializing to `Dictionary<string, Value>` clones appropriately, which means it's effectively an extension mechanism you can use if you want.

**Comment by pauloevpr** [comment]
Great news! I am looking forward to that. Thank you.

**Comment by jskeet** [comment]
Fixed; will release on Monday.

**Comment by moander** [comment]
Are there any examples available for how to store a simple poco class using Firestore in dotnet?

I come from the nodejs Firestore library where it is very straight forward.

**Comment by amanda-tarafa** [comment]
I think you are looking for something like this: [Writing Documents](http://googleapis.github.io/google-cloud-dotnet/docs/Google.Cloud.Firestore/userguide.html#writing-documents)

**Comment by jskeet** [comment]
And also this: http://googleapis.github.io/google-cloud-dotnet/docs/Google.Cloud.Firestore/datamodel.html

**Comment by moander** [comment]
Thank you very much. I still have issues though. Is it a bug that it fails for class Person? 

```csharp
// This works
await doc.CreateAsync(new
{
    Person = new
    {
        Name = "test"
    }
});

// ArgumentException Unable to convert value of type Person
await doc.CreateAsync(new
{
    Person = new Person
    {
        Name = "test"
    }
});

public class Person
{
    public string Name { get; set; }
}
```

**Comment by jskeet** [comment]
You haven't applied the attribute to the class and property. Do that as per examples and it should work fine. Sorry for being terse - doing this on a mobile in an airport.

**Comment by moander** [comment]
I know but I expected that plain objects like Person just works the same way anonymous types does.

Is there any reason for this design? Sorry for making you type on your mobile ;)

**Comment by jskeet** [comment]
Yes, serialising arbitrary types could easily end up causing problems. You need to use one of the options listed on the link I gave before. We're introducing more flexible serialisation with custom converters, but that wouldn't help in the example you gave.

**Comment by moander** [comment]
Ok, I got it working except for enums. Is there another attribute for enums? FirestoreData is for class only.

**Comment by jskeet** [comment]
Enums should just work, unless I neglected them accidentally. If so, please
file a new issue as we're now a very long way from this original issue.
